common:
    thread_num: 10,
    connection_count: 8,
    ignore_error_count: 2,
    http_proxy: null,
    https_proxy: null
    fuel: "http://localhost:8080"
    destination: "/var/www/nailgun"

versions:
    centos_version: "6"
    ubuntu_version: "trusty"

sources:
    -   name: "mos"
        osname: "ubuntu"
        type: "deb"
        baseurl: "http://mirror.fuel-infra.org/mos-repos/ubuntu/{mos_version}"
        repositories:
             - "mos{mos_version} main restricted"
             - "mos{mos_version}-updates main restricted"
             - "mos{mos_version}-security main restricted"
             - "mos{mos_version}-holdback main restricted"
        requirements:
             - "ubuntu-standard"

    -   name: "mos"
        osname: "centos"
        type: "yum"
        baseurl: "http://mirror.fuel-infra.org/mos-repos/centos/mos{mos_version}-centos{centos_version}-fuel"
        repositories:
            - "cr"
            - "holdback"
            - "os"
            - "security"
            - "updates"

    -   name: "ubuntu"
        osname: "ubuntu"
        type: "deb"
        master: "mos"
        baseurl: "http://archive.ubuntu.com/ubuntu"
        repositories:
            - "{ubuntu_version} main multiverse restricted universe"
            - "{ubuntu_version}-update main multiverse restricted universe"
            - "{ubuntu_version}-security main multiverse restricted universe"

    -   name: "centos"
        osname: "centos"
        type: "yum"
        master: "mos"
        baseurl: "http://mirror.centos.org/centos/{centos_version}"
        repositories:
            - "os"
            - "updates"
